/* Kindred Creatures — field-guide data: birds, young plumages, beyond-bird animals, sizes. Plain script; shares globals with the other js/ files (load order in index.html). */
/* ---------------- Data ---------------- */
const MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const SIZES=[
 {id:"tiny",label:"Tiny",hint:"hummingbird, kinglet"},
 {id:"small",label:"Small",hint:"sparrow, finch"},
 {id:"medium",label:"Medium",hint:"robin to jay"},
 {id:"large",label:"Large",hint:"crow, gull, hawk"},
 {id:"xlarge",label:"Huge",hint:"heron, pelican, goose"}];
const COLORS=[
 {id:"black",hex:"#1c1c22"},{id:"white",hex:"#f4f2ea"},{id:"gray",hex:"#8a8f96"},{id:"brown",hex:"#7a5436"},
 {id:"red",hex:"#c8322f"},{id:"orange",hex:"#e0782a"},{id:"yellow",hex:"#f2c92c"},{id:"green",hex:"#3f8f4e"},
 {id:"blue",hex:"#2f5fb3"},{id:"iridescent",hex:"conic-gradient(#7b2d8e,#2f8f7a,#2f5fb3,#c2185b,#7b2d8e)"}];
const SRC={
 andrews:"Ted Andrews writes about this bird in Animal Speak. Paraphrased here from his themes, not quoted — worth checking against your copy.",
 family:"Andrews writes about this bird's family or a close cousin; this carries his reading over to the San Francisco species.",
 folk:"As far as I know Andrews doesn't cover this one, so this reading comes from its own behavior and wider folklore.",
 lore:"From plant lore — the Victorian language of flowers, folk tradition and the plant's own nature. Andrews' Nature-Speak has a plant dictionary worth checking against your copy."};

// Shorthand palette colors
const K="#1c1c22",W="#f4f2ea",G="#8a8f96",LG="#c9ccd0",BR="#7a5436",LB="#b08a62",RD="#c8322f",OR="#e0782a",YL="#f2c92c",OL="#8a9a3c",GN="#3f8f4e",BL="#2f5fb3",RU="#b5552a";

const BIRDS=[
{id:"annas-hummingbird",name:"Anna's Hummingbird",size:"tiny",colors:["green","gray","red","iridescent"],shape:"hummer",months:"all",
 where:"Every garden and park with flowers, all year. Males dive-display in winter and spring.",
 m:{head:"#c2185b",throat:"#c2185b",back:"#4f8f3a",belly:"#aeb4a8",wing:"#56645a",tail:"#4f6a48"},
 f:{head:"#4f8f3a",throat:"#aeb4a8",patch:{at:"throat",c:"#c2185b",s:.5},back:"#4f8f3a",belly:"#c7c9c0",wing:"#56645a",tail:"#4f6a48"},
 mNote:"Rose-magenta crown and throat that flash in the light.",fNote:"Green above, gray below, a small red spot on the throat.",
 sym:{keys:["joy","tireless effort","sweetness"],src:"andrews",why:"Andrews links hummingbirds with the joy of simply being alive and with doing what looks impossible — tiny bodies, huge journeys, constant motion. Anna's stay in San Francisco all year, so this is a reminder of sweetness that doesn't leave with the seasons."}},
{id:"allens-hummingbird",name:"Allen's Hummingbird",size:"tiny",colors:["orange","green","iridescent"],shape:"hummer",months:"all",
 where:"Coastal scrub and gardens; SF has a year-round population. Spring is when you hear their buzzy wing trill most.",
 m:{head:"#4f8f3a",throat:"#e8552a",back:"#4f8f3a",belly:"#e39a5c",wing:"#56645a",tail:"#c9672e"},
 f:{head:"#4f8f3a",throat:"#e8e2d6",patch:{at:"throat",c:"#e8552a",s:.5},back:"#4f8f3a",belly:"#ecd0b4",wing:"#56645a",tail:"#c9672e"},
 mNote:"Copper-orange throat, rusty sides and tail, green back.",fNote:"Green back, pale throat with orange flecks, peachy sides.",
 sym:{keys:["fiery joy","courage","presence"],src:"family",why:"Andrews' hummingbird reading of joy and resilience applies here; Allen's add fire — the males are fearless defenders of their flowers. A nudge to guard what brings you delight."}},
{id:"black-phoebe",name:"Black Phoebe",size:"small",colors:["black","white"],shape:"song",beak:"thin",months:"all",
 where:"Near water: ponds in Golden Gate Park, lagoons, even garden fountains. Wags its tail on a low perch.",
 both:{head:"#26262c",back:"#2b2b31",belly:W,wing:"#34343b",tail:"#26262c"},
 sym:{keys:["patience","timing","returning"],src:"folk",why:"A flycatcher that flies out from one chosen perch again and again and returns — waiting, catching what comes, going back to center. A picture of steady patience and good timing."}},
{id:"american-robin",name:"American Robin",size:"medium",colors:["orange","gray","black"],shape:"song",beak:"thin",months:"all",
 where:"Lawns and parks; flocks swell in winter when they gather at berry trees.",
 both:{head:"#2d2d33",back:"#5d5a57",belly:"#d86a2a",wing:"#55524f",tail:"#2d2d33",beak:YL,eyeRing:W},
 sym:{keys:["new growth","fresh start","hope"],src:"andrews",why:"Andrews treats the robin as a herald of spring and of new growth in your own life, with the red breast tying it to life force. When a robin shows up, something is ready to begin."}},
{id:"california-scrub-jay",name:"California Scrub-Jay",size:"medium",colors:["blue","gray","white"],shape:"song",beak:"thick",months:"all",
 where:"Gardens, oak and scrub edges, parks citywide. Loud, bold, buries acorns.",
 both:{head:"#3a6fc2",back:"#8a8378",belly:LG,wing:"#3a6fc2",tail:"#3a6fc2",patch:{at:"breastband",c:"#3a6fc2"},face:"#5a6070"},
 sym:{keys:["right use of power","boldness","resourcefulness"],src:"family",why:"Andrews' blue jay reading is about using power well rather than scattering it — jays can be bold and loud, or wise and effective. Scrub-jays also plant thousands of acorns and remember them: a sign to put your energy where it will grow."}},
{id:"stellers-jay",name:"Steller's Jay",size:"medium",colors:["blue","black"],shape:"song",beak:"thick",crest:true,months:"all",
 where:"Conifers and forest: Presidio, Golden Gate Park, Mount Sutro.",
 both:{head:"#1e1e28",back:"#1f3f8a",belly:"#2c5aa8",wing:"#2f5fb3",tail:"#2a4f9e"},
 sym:{keys:["power","voice","forest wisdom"],src:"family",why:"Carries Andrews' jay themes of power and its right use. Steller's also mimic hawks, which adds a note about voice: what you say, and whether it's truly yours."}},
{id:"common-raven",name:"Common Raven",size:"large",colors:["black","iridescent"],shape:"song",beak:"thick",months:"all",
 where:"Increasingly common: Presidio, Twin Peaks, Ocean Beach, downtown. Listen for the deep croak.",
 both:{head:"#17171d",back:"#1c1c24",belly:"#22222b",wing:"#262633",tail:"#17171d",patch:{at:"throat",c:"#2a2a3a"}},
 sym:{keys:["magic","shapeshifting","messages"],src:"andrews",why:"Andrews connects the raven with magic, with shifts in consciousness and with messages from the unseen. It's often read as a sign that change is already underway and asking for your attention."}},
{id:"american-crow",name:"American Crow",size:"large",colors:["black"],shape:"song",beak:"thick",months:"all",
 where:"Parks, streets, everywhere; roosting flocks at dusk.",
 both:{head:"#1a1a20",back:"#1d1d24",belly:"#22222a",wing:"#27272f",tail:"#1a1a20"},
 sym:{keys:["everyday magic","sacred law","watchfulness"],src:"andrews",why:"Andrews sees the crow as a keeper of spiritual law and a reminder that magic lives in ordinary days. Crows watch closely and remember faces — a prompt to walk your talk."}},
{id:"rock-pigeon",name:"Rock Pigeon",size:"medium",colors:["gray","iridescent","white"],shape:"dove",months:"all",
 where:"Plazas, rooftops, sidewalks — the city's constant companion.",
 both:{head:"#6b7280",throat:"#3f7f6f",back:"#9aa0a8",belly:"#8e949c",wing:"#aab0b8",tail:"#6b7280",patch:{at:"breastband",c:"#7a4a8a"},eye:"#d0602a",bars:true},
 sym:{keys:["home","belonging","return"],src:"andrews",why:"Andrews ties pigeons to the pull of home and to feeling secure where you belong — homing pigeons always find their way back. A city bird for coming home to yourself."}},
{id:"mourning-dove",name:"Mourning Dove",size:"medium",colors:["brown","gray"],shape:"dove",months:"all",
 where:"Gardens and wires across the Sunset and Richmond; the soft cooing at dawn.",
 both:{head:"#b8a590",back:"#a08c74",belly:"#cdb8a0",wing:"#9c8a74",tail:"#8d7b66",spots:true},
 sym:{keys:["peace","prophecy","gentleness"],src:"andrews",why:"Andrews links the dove to peace, to gentle feminine energy and to prophecy — its mourning call is heard as a voice for what's coming and what's being released."}},
{id:"house-finch",name:"House Finch",size:"small",colors:["red","brown"],shape:"song",beak:"cone",months:"all",
 where:"Feeders, balconies, parks; bright warbled songs from rooftops.",
 m:{head:"#c8322f",throat:"#c8322f",back:"#7a5d45",belly:"#d9c8b0",wing:"#6a5040",tail:"#6a5040",patch:{at:"breastband",c:"#d0413a"},streaks:true},
 f:{head:"#8a7560",back:"#7a6550",belly:"#d6cab8",wing:"#6a5a48",tail:"#6a5a48",streaks:true},
 mNote:"Red head, breast and rump over streaky brown.",fNote:"Plain brown, streaked all over — no red.",
 sym:{keys:["variety","liveliness","song"],src:"family",why:"Andrews reads finches as birds of variety and lively activity — lots of experiences and lots of song. A sign to let life be colorful and many-sided."}},
{id:"lesser-goldfinch",name:"Lesser Goldfinch",size:"small",colors:["yellow","black","green"],shape:"song",beak:"cone",months:"all",
 where:"Weedy edges, gardens with seedheads; sweet, wheezy calls.",
 m:{head:"#6f8a2a",cap:K,back:"#6f8a2a",belly:"#f2d42c",wing:K,tail:K,patch:{at:"shoulder",c:W}},
 f:{head:"#8a9a3c",back:"#8a9a3c",belly:"#e6d56a",wing:"#3a3a3a",tail:"#3a3a3a"},
 mNote:"Black cap, green back, lemon-yellow below.",fNote:"Olive above, soft yellow below, no cap.",
 sym:{keys:["lightness","nature spirits","brightness"],src:"family",why:"Andrews connects goldfinches with the nature spirits and the lighter, playful side of life. A little yellow bird in the weeds is an invitation to notice the enchantment in small places."}},
{id:"american-goldfinch",name:"American Goldfinch",size:"small",colors:["yellow","black","white"],shape:"song",beak:"cone",months:"10-4",
 where:"Mostly fall and winter visitors; look in weedy fields and at thistle feeders.",
 m:{head:"#f5d400",cap:K,back:"#f5d400",belly:"#f5d400",wing:K,tail:K,beak:"#e8a26a",bars:true},
 f:{head:"#b3ab52",back:"#9a9a4a",belly:"#e2d98a",wing:"#2a2a2a",tail:"#2a2a2a",beak:"#e8a26a",bars:true},
 mNote:"Breeding male: bright yellow, black cap and wings (duller in winter).",fNote:"Olive-yellow with dark wings and pale wing bars.",
 sym:{keys:["lightness","nature spirits","joy"],src:"andrews",why:"Andrews writes about the goldfinch as a link to the nature spirits and the sunny, lighter aspects of life. Here in SF it's mostly a winter visitor — brightness in the dark months."}},
{id:"white-crowned-sparrow",name:"White-crowned Sparrow",size:"small",colors:["brown","gray","white","black"],shape:"song",beak:"cone",months:"all",
 where:"Everywhere with shrubs. SF's own Nuttall's subspecies sings local dialects all year; more arrive in winter.",
 both:{head:"#a7abb0",cap:K,crownStripe:W,back:"#8a6a4a",belly:"#b9bcbf",wing:"#7a5a3e",tail:"#7a5a3e",beak:"#e8b24a",bars:true,streaks:true},
 sym:{keys:["self-worth","dialect","persistence"],src:"family",why:"Andrews' sparrow reading is about awakening your sense of self-worth — the common bird who still matters. White-crowns here learn neighborhood song dialects, so there's also a note about finding your own voice where you live."}},
{id:"song-sparrow",name:"Song Sparrow",size:"small",colors:["brown","white"],shape:"song",beak:"cone",months:"all",
 where:"Damp brushy spots: lake edges, Presidio creeks, Heron's Head Park.",
 both:{head:"#8a6448",back:"#7d5c42",belly:"#ece6da",wing:"#6e4f37",tail:"#6e4f37",streaks:true,patch:{at:"breastband",c:"#5a3c28",s:.7}},
 sym:{keys:["self-worth","expression","simple beauty"],src:"family",why:"Carries Andrews' sparrow themes of self-worth and dignity. Song sparrows sing from the most ordinary bush with full hearts — you don't need a grand stage to be heard."}},
{id:"dark-eyed-junco",name:"Dark-eyed Junco",size:"small",colors:["gray","black","brown","white"],shape:"song",beak:"cone",months:"all",
 where:"Parks and gardens under shrubs; flashes white outer tail feathers when it flies.",
 m:{head:"#25252c",throat:"#25252c",back:"#8a6040",belly:"#efece6",wing:"#6a6060",tail:"#3a3a40",beak:"#e8b8b0"},
 f:{head:"#6e6e74",throat:"#6e6e74",back:"#8f7058",belly:"#efece6",wing:"#747070",tail:"#555558",beak:"#e8b8b0"},
 mNote:"Black hood, rusty back, pink bill.",fNote:"Grayer, softer hood; same pink bill.",
 sym:{keys:["grounding","belonging","seasons"],src:"folk",why:"Juncos forage on the ground in little flocks and follow the seasons closely. They suggest staying close to the earth, and finding your people for the season you're in."}},
{id:"spotted-towhee",name:"Spotted Towhee",size:"small",colors:["black","orange","white"],shape:"song",beak:"cone",months:"all",
 where:"Dense thickets: Presidio, Glen Canyon, Bayview Hill. Loud scratching in leaves.",
 m:{head:K,throat:K,back:"#1f1f24",belly:W,wing:"#1f1f24",tail:K,patch:{at:"side",c:"#c0602a"},spots:true,eye:"#c8322f"},
 f:{head:"#4a3a30",throat:"#4a3a30",back:"#443a32",belly:W,wing:"#443a32",tail:"#3a3028",patch:{at:"side",c:"#c0602a"},spots:true,eye:"#c8322f"},
 mNote:"Black hood and back with white spots, rusty sides, red eye.",fNote:"Same pattern in warm brown instead of black.",
 sym:{keys:["attention","rootedness","searching"],src:"folk",why:"Towhees scratch through leaf litter with both feet at once, looking under what everyone else walks over. A sign to look carefully at what's right in front of you."}},
{id:"california-towhee",name:"California Towhee",size:"small",colors:["brown"],shape:"song",beak:"cone",months:"all",
 where:"Brushy gardens and scrub, often in pairs that stay together.",
 both:{head:"#8a7460",back:"#86705c",belly:"#a8927c",wing:"#7a6452",tail:"#7a6452",throat:"#c89060"},
 sym:{keys:["contentment","partnership","humility"],src:"folk",why:"A plain brown bird that mates for life and stays on the same patch of ground for years. It speaks of quiet contentment and the beauty of the modest and steady."}},
{id:"chestnut-backed-chickadee",name:"Chestnut-backed Chickadee",size:"tiny",colors:["brown","black","white"],shape:"song",beak:"thin",months:"all",
 where:"Trees in Golden Gate Park, the Presidio, backyard feeders; busy in mixed flocks.",
 both:{head:"#e8e3da",cap:"#2a2320",throat:"#2a2320",back:"#9b4a2a",belly:"#e8e3da",wing:"#6a6a6a",tail:"#6a6a6a",patch:{at:"side",c:"#a8583a"}},
 sym:{keys:["cheer","truth","expression"],src:"family",why:"Andrews associates chickadees with cheerfulness and with truthful expression — their call is literally their name. A reminder to speak plainly and kindly."}},
{id:"bushtit",name:"Bushtit",size:"tiny",colors:["gray","brown"],shape:"song",beak:"short",tail:52,months:"all",
 where:"Chattering flocks moving through shrubs in every park; they build hanging sock-shaped nests.",
 m:{head:"#9a8f84",back:"#8f949a",belly:"#c9c6c0",wing:"#7e848a",tail:"#7e848a",eye:"#1a1a1a"},
 f:{head:"#9a8f84",back:"#8f949a",belly:"#c9c6c0",wing:"#7e848a",tail:"#7e848a",eye:"#e8d27a"},
 mNote:"Dark eye.",fNote:"Pale yellow eye — the only easy way to tell them apart.",
 sym:{keys:["community","togetherness","small things"],src:"folk",why:"Tiny birds that travel and even sleep huddled in flocks. They speak to belonging, and to how many small efforts together build something whole."}},
{id:"pygmy-nuthatch",name:"Pygmy Nuthatch",size:"tiny",colors:["gray","brown","white"],shape:"song",beak:"thin",tail:22,months:"all",
 where:"Pine and cypress in Golden Gate Park and the Presidio; squeaky flocks high in the trees.",
 both:{head:"#e8e4dc",cap:"#7a6450",back:"#7f8a96",belly:"#e5e1d8",wing:"#6f7a86",tail:"#6f7a86"},
 sym:{keys:["grounded faith","new perspective","trust"],src:"family",why:"Andrews connects nuthatches with grounded faith — they walk head-first down trees, trusting their grip. A sign to look at your situation from a different angle."}},
{id:"ruby-crowned-kinglet",name:"Ruby-crowned Kinglet",size:"tiny",colors:["green","gray","red","white"],shape:"song",beak:"thin",tail:26,months:"9-4",
 where:"Winter visitor in shrubs and trees citywide; constantly flicks its wings.",
 m:{head:"#8a9a5a",back:"#7f9050",belly:"#d6dab8",wing:"#5a6a3a",tail:"#5a6a3a",patch:{at:"crown",c:"#d8243a"},eyeRing:W,bars:true},
 f:{head:"#8a9a5a",back:"#7f9050",belly:"#d6dab8",wing:"#5a6a3a",tail:"#5a6a3a",eyeRing:W,bars:true},
 mNote:"Hidden red crown he raises when excited.",fNote:"No red; olive with a white eye ring.",
 sym:{keys:["inner fire","energy","hidden gifts"],src:"folk",why:"A tiny olive bird with a secret red crown it only shows when stirred up. It points to gifts you carry that don't need to be on display all the time."}},
{id:"yellow-rumped-warbler",name:"Yellow-rumped Warbler",size:"small",colors:["yellow","gray","white","black"],shape:"song",beak:"thin",months:"9-4",
 where:"SF's most common winter warbler — parks, street trees, even beaches.",
 m:{head:"#6e747c",back:"#6e747c",belly:W,wing:"#4a4e56",tail:"#3a3e46",throat:YL,patch:{at:"side",c:YL},streaks:true,bars:true},
 f:{head:"#8a8278",back:"#8a8278",belly:"#ece8e0",wing:"#6a6660",tail:"#5a5650",throat:"#e8d890",patch:{at:"side",c:"#e8c83a"},streaks:true,bars:true},
 mNote:"Gray with yellow throat, side patches and rump.",fNote:"Browner and softer, same yellow spots.",
 sym:{keys:["cheer","adaptability","passing through"],src:"folk",why:"A winter visitor that can live on berries when insects are scarce — flexible and bright in gray months. It suggests that a visiting mood or phase can still bring gifts."}},
{id:"townsends-warbler",name:"Townsend's Warbler",size:"small",colors:["yellow","black","green"],shape:"song",beak:"thin",months:"9-4",
 where:"Winter visitor high in cypress and pines; Golden Gate Park and the Presidio.",
 m:{head:YL,face:K,throat:K,back:"#7a8a3a",belly:"#f2e070",wing:"#4a4e56",tail:"#4a4e56",streaks:true,bars:true},
 f:{head:YL,face:"#6a6a50",throat:YL,back:"#8a9a4a",belly:"#f2e490",wing:"#5a5e60",tail:"#5a5e60",bars:true},
 mNote:"Black cheek and throat framed in yellow.",fNote:"Yellow throat, olive cheek patch.",
 sym:{keys:["clarity","brightness","attention"],src:"folk",why:"Bold face markings on a treetop bird — you have to look up and pay attention to see it. A sign to lift your gaze."}},
{id:"wilsons-warbler",name:"Wilson's Warbler",size:"small",colors:["yellow","green","black"],shape:"song",beak:"thin",months:"4-9",
 where:"Spring and summer in willows and moist thickets; breeds in the Presidio.",
 m:{head:YL,cap:K,back:"#8a9a2a",belly:"#f5d82a",wing:"#8a9a2a",tail:"#7a8a2a"},
 f:{head:YL,cap:"#7a8a3a",back:"#8a9a2a",belly:"#f2d84a",wing:"#8a9a2a",tail:"#7a8a2a"},
 mNote:"Crisp black cap on bright yellow.",fNote:"Cap faint or olive.",
 sym:{keys:["sunshine","small courage","renewal"],src:"folk",why:"It arrives in spring from far to the south, a spark of pure yellow. A reminder that the light returns and that small beings make big journeys."}},
{id:"hooded-oriole",name:"Hooded Oriole",size:"medium",colors:["orange","yellow","black","white"],shape:"song",beak:"thin",months:"3-9",
 where:"Spring and summer, nesting in palm trees — Mission, Dolores, Sunset palms.",
 m:{head:"#f0a22a",throat:K,face:K,back:"#f0a22a",belly:"#f2b83a",wing:K,tail:K,bars:true},
 f:{head:"#cbc05a",back:"#a8a45a",belly:"#e2d06a",wing:"#6a6a66",tail:"#8a8a50",bars:true},
 mNote:"Flame orange with a black face and throat.",fNote:"Olive-yellow with grayish wings.",
 sym:{keys:["sunny heart","joy","summer"],src:"family",why:"Andrews reads orioles as birds of a sunny disposition and cheerful energy. Hooded orioles literally sew their nests to palm fronds — joy with a home built in."}},
{id:"northern-mockingbird",name:"Northern Mockingbird",size:"medium",colors:["gray","white"],shape:"song",beak:"thin",tail:48,months:"all",
 where:"Rooftops and treetops; famous for singing at night in spring.",
 both:{head:"#8a8f96",back:"#7f848b",belly:"#e8e6e0",wing:"#4a4e56",tail:"#3a3e46",patch:{at:"shoulder",c:W},eye:"#d6a53a"},
 sym:{keys:["your true song","many voices","expression"],src:"andrews",why:"Andrews connects the mockingbird with finding your own song — it holds many voices, and the question is which one is really yours. A nudge toward your calling."}},
{id:"european-starling",name:"European Starling",size:"medium",colors:["black","iridescent","white"],shape:"song",beak:"thin",tail:24,months:"all",
 where:"Lawns, wires, and huge swirling flocks; introduced from Europe.",
 both:{head:"#1f2230",back:"#26283a",belly:"#2a2d40",wing:"#34304a",tail:"#1f2230",beak:YL,spots:true,throat:"#3a2a5a"},
 sym:{keys:["group harmony","communication","etiquette"],src:"andrews",why:"Andrews associates starlings with group behavior and etiquette — how we move together and communicate. A murmuration is the image: many, moving as one."}},
{id:"brewers-blackbird",name:"Brewer's Blackbird",size:"medium",colors:["black","brown","iridescent"],shape:"song",beak:"thin",months:"all",
 where:"Parking lots, lawns, outdoor cafés — confident walkers.",
 m:{head:"#1a1a2e",back:"#1c1e30",belly:"#20223a",wing:"#243048",tail:"#1a1a2e",eye:"#f2e04a",throat:"#2a2a5a"},
 f:{head:"#6a5a4e",back:"#5e5046",belly:"#6e5e52",wing:"#524840",tail:"#4a4038",eye:"#1a1a1a"},
 mNote:"Glossy black with purple-green sheen and a bright yellow eye.",fNote:"Plain brown with a dark eye.",
 sym:{keys:["mystery","harmony","confidence"],src:"family",why:"Andrews connects blackbirds with the mystical side of nature and its harmonies. Brewer's strut among people without fear — the magical showing up in parking lots."}},
{id:"red-winged-blackbird",name:"Red-winged Blackbird",size:"medium",colors:["black","red","brown","yellow"],shape:"song",beak:"thin",months:"all",
 where:"Cattails and marsh edges: Lake Merced, Heron's Head, the Presidio's Crissy marsh.",
 m:{head:"#17171d",back:"#1a1a20",belly:"#1e1e25",wing:"#1a1a20",tail:"#17171d",patch:{at:"shoulder",c:"#d3302a",edge:"#f2c92c"}},
 f:{head:"#7a5a40",back:"#5e4432",belly:"#d8c8b0",wing:"#4e3a2a",tail:"#4a3628",streaks:true},
 mNote:"Black with red-and-yellow shoulder patches.",fNote:"Streaky brown, sparrow-like.",
 sym:{keys:["nature's harmony","intuition","claiming space"],src:"andrews",why:"Andrews ties the red-winged blackbird to the mystical harmony of the natural world. The males flare those red shoulders to claim their spot — a reminder you're allowed to take up space."}},
{id:"cedar-waxwing",name:"Cedar Waxwing",size:"small",colors:["brown","yellow","gray","red","black"],shape:"song",beak:"short",crest:true,months:"11-5",
 where:"Wandering winter flocks that strip berry trees; high thin whistles.",
 both:{head:"#b8905a",face:K,back:"#a8885e",belly:"#d8c890",wing:"#6e747c",tail:"#6e747c",tailTip:YL,patch:{at:"shoulder",c:"#d8243a",s:.5}},
 sym:{keys:["sharing","generosity","sweetness"],src:"folk",why:"Waxwings pass berries bird to bird down a branch, sharing food. Silky and gentle, they're a picture of generosity and savoring sweetness together."}},
{id:"western-bluebird",name:"Western Bluebird",size:"small",colors:["blue","orange","gray"],shape:"song",beak:"thin",months:"all",
 where:"The Presidio's open woodlands, after a successful reintroduction.",
 m:{head:"#2c5cc0",throat:"#2c5cc0",back:"#2c5cc0",belly:"#c86a38",wing:"#3a6ad0",tail:"#3a6ad0"},
 f:{head:"#8a909a",throat:"#a8a8a8",back:"#8a909a",belly:"#e0a878",wing:"#7a96c8",tail:"#7a96c8",eyeRing:W},
 mNote:"Deep blue with a rusty breast.",fNote:"Gray-blue head, soft orange wash, blue in the wings.",
 sym:{keys:["happiness","modesty","quiet confidence"],src:"andrews",why:"Andrews links bluebirds with happiness and unassuming confidence — joy that doesn't need to show off. Their return to the Presidio makes them a sign of things coming back."}},
{id:"barn-swallow",name:"Barn Swallow",size:"small",colors:["blue","orange","white"],shape:"song",beak:"short",tail:46,months:"3-10",
 where:"Spring through fall over fields and water; nests under eaves and bridges.",
 both:{head:"#23408a",throat:"#b0502a",back:"#23408a",belly:"#e8c8a8",wing:"#1e3470",tail:"#1e3470",fork:true},
 sym:{keys:["protection","home","hope"],src:"andrews",why:"Andrews associates swallows with protection and with finding or making a home. Sailors saw them as signs of land — a hopeful arrival."}},
{id:"downy-woodpecker",name:"Downy Woodpecker",size:"small",colors:["black","white","red"],shape:"song",beak:"chisel",tail:26,months:"all",
 where:"Trees in Golden Gate Park, the Presidio, and leafy backyards; soft tapping.",
 m:{head:W,cap:K,face:K,back:K,belly:W,wing:K,tail:K,patch:{at:"nape",c:RD},spots:true},
 f:{head:W,cap:K,face:K,back:K,belly:W,wing:K,tail:K,spots:true},
 mNote:"Small red patch on the back of the head.",fNote:"No red.",
 sym:{keys:["rhythm","discernment","opportunity"],src:"family",why:"Andrews connects woodpeckers with rhythm and with discernment — knowing where to tap. A sign to follow your own rhythm and knock on the right doors."}},
{id:"northern-flicker",name:"Northern Flicker",size:"medium",colors:["brown","black","orange","gray"],shape:"song",beak:"chisel",months:"9-4",
 where:"Mostly fall and winter; often on the ground eating ants in parks and lawns. Salmon-red flashes under the wings.",
 m:{head:"#8a8f96",cap:"#b08a62",back:"#9a7a5a",belly:"#e8d8c0",wing:"#8a6a4a",tail:K,patch:{at:"mustache",c:RD},spots:true,bars:true},
 f:{head:"#8a8f96",cap:"#b08a62",back:"#9a7a5a",belly:"#e8d8c0",wing:"#8a6a4a",tail:K,spots:true,bars:true},
 mNote:"Red 'mustache' stripe.",fNote:"No mustache.",
 sym:{keys:["new rhythm","healing","trust"],src:"andrews",why:"Andrews writes of the flicker as bringing a new rhythm of growth and healing. It feeds on the ground and drums on trees — between earth and sky."}},
{id:"belted-kingfisher",name:"Belted Kingfisher",size:"medium",colors:["blue","white","orange","gray"],shape:"song",beak:"chisel",crest:true,headBig:true,months:"8-4",
 where:"Lakes and lagoons, mostly fall–spring: Stow Lake, Lake Merced, Mountain Lake. Rattling call.",
 m:{head:"#4a6a9a",throat:W,back:"#4a6a9a",belly:W,wing:"#3a5a8a",tail:"#3a5a8a",patch:{at:"breastband",c:"#4a6a9a"}},
 f:{head:"#4a6a9a",throat:W,back:"#4a6a9a",belly:W,wing:"#3a5a8a",tail:"#3a5a8a",patch:{at:"breastband",c:"#4a6a9a"},patch2:{at:"side",c:"#c0602a"}},
 mNote:"Blue-gray breast band.",fNote:"Blue band plus a rusty belly band — the female is the more colorful one.",
 sym:{keys:["abundance","warmth","new opportunity"],src:"andrews",why:"Andrews associates the kingfisher with prosperity, warmth and love. It dives into water and comes up with what it needs — an image of opportunities surfacing."}},
{id:"red-masked-parakeet",name:"Wild Parrots (Red-masked Parakeet)",size:"medium",colors:["green","red"],shape:"song",beak:"hook",tail:62,months:"all",
 where:"The famous flock of Telegraph Hill and the Embarcadero, descended from escaped pets.",
 both:{head:"#d8243a",back:"#3aa04a",belly:"#4ab85a",wing:"#2f8f3e",tail:"#3a9a4a",beak:"#e8d8b8",eyeRing:W},
 sym:{keys:["color","healing","voice"],src:"family",why:"Andrews connects parrots with color, sunlight, and healing, and with the power of speech. SF's wild flock is also a story of making a home somewhere unexpected."}},
{id:"california-quail",name:"California Quail",size:"medium",colors:["gray","brown","black","white"],shape:"quail",months:"all",
 where:"San Francisco's official bird — very rare in the city now; a small group persists in Golden Gate Park and reintroduction efforts continue.",
 m:{head:"#6e747c",cap:"#8a5a3a",face:K,throat:K,back:"#8a7a6a",belly:"#9aa0a8",wing:"#8a7058",tail:"#6a6060",plume:K,scales:true},
 f:{head:"#8a7a6a",back:"#8a7a6a",belly:"#a8a098",wing:"#8a7058",tail:"#6a6060",plume:"#5a4a3a",scales:true},
 mNote:"Black face outlined in white, big forward plume.",fNote:"Plain brown face, smaller plume.",
 sym:{keys:["group harmony","protection","home ground"],src:"andrews",why:"Andrews connects quail with group harmony and protection — coveys move and watch out for one another. As SF's own bird, it's also about caring for where you live."}},
{id:"killdeer",name:"Killdeer",size:"medium",colors:["brown","white","black","orange"],shape:"song",beak:"short",long:true,months:"all",
 where:"Open ground: Lake Merced, fields, gravel lots. Calls its own name.",
 both:{head:"#8a6a4a",face:W,back:"#8a6a4a",belly:W,wing:"#7a5a3e",tail:"#c0702a",patch:{at:"breastband",c:K},eyeRing:"#e0602a"},
 sym:{keys:["protection","clever care","boundaries"],src:"folk",why:"A killdeer pretends to have a broken wing to lead danger away from its nest. It's about protecting what's precious with creativity rather than force."}},
{id:"hermit-thrush",name:"Hermit Thrush",size:"small",colors:["brown","white"],shape:"song",beak:"thin",months:"10-4",
 where:"Quiet winter visitor in shady undergrowth; raises and lowers its rusty tail.",
 both:{head:"#8a7058",back:"#8a7058",belly:"#ece6dc",wing:"#7a6048",tail:"#a8603a",spots:true,eyeRing:W},
 sym:{keys:["inner song","solitude","quiet beauty"],src:"folk",why:"In summer forests elsewhere its song is one of the most beautiful in North America; in SF in winter it's nearly silent. A reminder that beauty can rest quietly inside you, waiting."}},
{id:"mallard",name:"Mallard",size:"large",colors:["green","brown","gray","white","blue"],shape:"duck",months:"all",
 where:"Every pond and lake: Stow Lake, Spreckels, Lake Merced.",
 m:{head:"#1f7a4a",throat:"#1f7a4a",back:"#9aa0a0",belly:"#c8ccd0",wing:"#8a8a8a",tail:K,beak:"#e8d02a",patch:{at:"breastband",c:"#7a3a2a"},speculum:BL},
 f:{head:"#a08060",back:"#8a6a4a",belly:"#b89878",wing:"#7a5a40",tail:"#7a5a40",beak:"#e0802a",speculum:BL,scales:true},
 mNote:"Green head, white collar, chestnut breast, yellow bill.",fNote:"Mottled brown, orange-and-dark bill, blue wing patch.",
 sym:{keys:["emotional comfort","ease","protection"],src:"andrews",why:"Andrews connects ducks with emotional comfort and protection — they're at home in water, which often stands for feeling. A sign to be gentle with your emotional life."}},
{id:"bufflehead",name:"Bufflehead",size:"medium",colors:["black","white","iridescent"],shape:"duck",months:"10-4",
 where:"Winter on lakes and the bay: Lake Merced, Heron's Head, Crissy Field lagoon.",
 m:{head:"#2a2a4a",throat:"#1f5a4a",patch:{at:"cheekbig",c:W},back:K,belly:W,wing:K,tail:"#6a6a6a",beak:"#6a6a70"},
 f:{head:"#4a4440",patch:{at:"cheek",c:W},back:"#4a4440",belly:"#a8a4a0",wing:"#3a3634",tail:"#3a3634",beak:"#4a4a50"},
 mNote:"Big white head patch, white body.",fNote:"Dusky brown with a white cheek spot.",
 sym:{keys:["playfulness","buoyancy","diving in"],src:"family",why:"Andrews' duck reading of emotional comfort applies; buffleheads add constant, bouncy diving. They suggest you can go deep into feelings and pop right back up."}},
{id:"canada-goose",name:"Canada Goose",size:"xlarge",colors:["brown","black","white","gray"],shape:"goose",months:"all",
 where:"Lakes and lawns: Lake Merced, Golden Gate Park's meadows.",
 both:{head:K,throat:K,patch:{at:"cheekbig",c:W},back:"#7a6a5a",belly:"#c8bca8",wing:"#6a5a4a",tail:K,beak:K,scales:true},
 sym:{keys:["the quest","journeys","storytelling"],src:"andrews",why:"Andrews ties geese to the quest — travel to faraway places and the stories that come from the journey. Their V-shaped flights also say something about sharing the lead."}},
{id:"western-gull",name:"Western Gull",size:"large",colors:["white","gray"],shape:"gull",months:"all",
 where:"The coastline, piers, rooftops — nests on Alcatraz and the Farallones.",
 both:{head:W,back:"#5e646c",belly:W,wing:"#5e646c",tail:W,beak:"#f2c92c",leg:"#e8a8a0"},
 sym:{keys:["responsibility","communication","adaptability"],src:"andrews",why:"Andrews associates gulls with responsible behavior and clear communication — they're loud, social, and at home between land and sea. A prompt to say what you mean, considerately."}},
{id:"brown-pelican",name:"Brown Pelican",size:"xlarge",colors:["brown","gray","white","yellow"],shape:"pelican",months:"5-12",
 where:"Mostly summer and fall: lines of them gliding over Ocean Beach, Crissy Field, the piers.",
 both:{head:"#f2e8c0",cap:"#f2d27a",throat:"#6a3a2a",back:"#8a8f96",belly:"#6e6a6a",wing:"#7a7f86",tail:"#5a5e66",beak:"#c8a878"},
 sym:{keys:["generosity","buoyancy","rising again"],src:"andrews",why:"Andrews connects the pelican with unselfishness and with buoyancy — the ability to rise back up after going under. Its dive into the waves and bob back up is the lesson."}},
{id:"double-crested-cormorant",name:"Double-crested Cormorant",size:"large",colors:["black"],shape:"cormorant",months:"all",
 where:"Piers, rocks, Lake Merced; often perched with wings spread to dry.",
 both:{head:"#1a1a20",face:"#e8902a",back:"#22262a",belly:"#1a1a20",wing:"#2a3030",tail:"#1a1a20",beak:"#5a5a5a",eye:"#3aa0a0",scales:true},
 sym:{keys:["diving deep","openness","persistence"],src:"folk",why:"Cormorants dive deep, then stand with wings open to dry in the sun. It suggests going deep into something and then letting yourself be seen, unguarded."}},
{id:"great-blue-heron",name:"Great Blue Heron",size:"xlarge",colors:["gray","blue","white"],shape:"wader",months:"all",
 where:"Lake edges, marshes, and even Golden Gate Park lawns hunting gophers.",
 both:{head:W,face:K,neck:"#8a8a96",back:"#6a7a90",belly:"#6a7a90",wing:"#5e7088",tail:"#5e7088",beak:"#d8a83a",leg:"#6a6050",plume:K},
 sym:{keys:["self-determination","self-reliance","stillness"],src:"andrews",why:"Andrews connects the heron with self-determination and self-reliance — following your own path and not needing to fit in. Its long stillness before the strike is part of the medicine."}},
{id:"great-egret",name:"Great Egret",size:"xlarge",colors:["white","yellow"],shape:"wader",months:"all",
 where:"Marshes and lakes: Lake Merced, Heron's Head, Crissy lagoon.",
 both:{head:W,neck:W,back:W,belly:"#eeeee6",wing:"#f0efe8",tail:W,beak:"#f2c92c",leg:K},
 sym:{keys:["grace","self-reliance","purity"],src:"family",why:"Carries Andrews' heron themes of self-determination. Egrets add a sense of grace and purity — once nearly hunted out for their plumes, they're also a story of return."}},
{id:"snowy-egret",name:"Snowy Egret",size:"large",colors:["white","yellow","black"],shape:"wader",months:"all",
 where:"Shallow water at Crissy Field, Heron's Head, Lake Merced; stirs water with its golden feet.",
 both:{head:W,neck:W,back:W,belly:"#eeeee6",wing:"#f0efe8",tail:W,beak:K,leg:K,feet:YL,plume:"#f4f2ea"},
 sym:{keys:["stirring things up","grace","light"],src:"family",why:"Andrews' heron family reading applies. Snowy egrets shuffle their bright yellow feet to stir up food — sometimes you have to stir the waters to see what's there."}},
{id:"black-crowned-night-heron",name:"Black-crowned Night-Heron",size:"large",colors:["black","gray","white"],shape:"nightheron",months:"all",
 where:"Roosting in trees by water: Stow Lake, Lake Merced, the Embarcadero; active at dusk.",
 both:{head:W,cap:"#1f2a3a",back:"#1f2a3a",belly:"#dcdcd8",wing:"#9aa0a8",tail:"#9aa0a8",beak:K,leg:"#d8c84a",eye:"#d8243a",plume:W},
 sym:{keys:["twilight wisdom","patience","in-between"],src:"family",why:"Andrews' heron themes of self-reliance, with a twist: this one hunts at dusk and night. It speaks to insight that comes in between-times and quiet hours."}},
{id:"red-tailed-hawk",name:"Red-tailed Hawk",size:"large",colors:["brown","white","orange"],shape:"raptor",months:"all",
 where:"Soaring over parks, Twin Peaks, freeways; perched on light poles.",
 both:{head:"#7a5436",back:"#6a4a30",belly:"#ece2d0",wing:"#6a4a30",tail:"#c8602a",beak:"#3a3a3a",leg:YL,patch:{at:"bellyband",c:"#7a5436"}},
 sym:{keys:["vision","messenger","awakening"],src:"andrews",why:"Andrews writes about the hawk as a messenger and a bird of vision — seeing the larger picture — and the red-tail in particular with rising life force. Often read as a call to pay attention: a message is coming."}},
{id:"coopers-hawk",name:"Cooper's Hawk",size:"large",colors:["gray","orange","white"],shape:"raptor",months:"all",
 where:"Hunts songbirds at feeders and in parks; nests in city trees.",
 both:{head:"#5a6070",cap:"#2a3040",back:"#5a6070",belly:"#e8c8a8",wing:"#5a6070",tail:"#5a6070",beak:"#3a3a3a",leg:YL,eye:"#d8602a",bars:true},
 sym:{keys:["focus","swift action","clarity"],src:"family",why:"Carries Andrews' hawk themes of vision and messages. Cooper's hawks weave fast through trees — a sign to focus fully and move decisively."}},
{id:"american-kestrel",name:"American Kestrel",size:"medium",colors:["orange","blue","white","black"],shape:"raptor",months:"all",
 where:"Open ground and edges; hovers in place over fields. Uncommon in the city, more in winter.",
 m:{head:"#c8ccd0",cap:"#6a7aa8",face:K,back:"#c8602a",belly:"#f0e0c8",wing:"#6a7aa8",tail:"#c8602a",beak:"#3a3a3a",leg:YL,spots:true},
 f:{head:"#c8ccd0",cap:"#8a7a6a",face:K,back:"#b8602a",belly:"#f0e0c8",wing:"#b8602a",tail:"#b8602a",beak:"#3a3a3a",leg:YL,bars:true},
 mNote:"Blue-gray wings, rusty back.",fNote:"Rusty wings barred with black.",
 sym:{keys:["precision","speed","control"],src:"andrews",why:"Andrews connects the kestrel with speed, grace, and control of movement — it can hover perfectly still before it drops. Timing and accuracy are the gifts here."}},
{id:"peregrine-falcon",name:"Peregrine Falcon",size:"large",colors:["gray","white","black"],shape:"raptor",months:"all",
 where:"Nests on downtown towers and the Bay Bridge; watch for stoops over the Financial District.",
 both:{head:"#3a4050",face:"#3a4050",back:"#5a6070",belly:"#ece8e0",wing:"#4a5060",tail:"#4a5060",beak:"#3a3a3a",leg:YL,bars:true,eyeRing:YL},
 sym:{keys:["focus","swift change","recovery"],src:"family",why:"Carries Andrews' falcon reading around focus and healing. Peregrines nearly vanished and came back, now living on skyscrapers — a story of recovery and of thriving in unlikely places."}},
{id:"turkey-vulture",name:"Turkey Vulture",size:"xlarge",colors:["black","brown","red"],shape:"raptor",months:"all",
 where:"Teetering in the wind over the Presidio and western hills; more in fall.",
 both:{head:"#c8302a",back:"#3a2e2a",belly:"#3a2e2a",wing:"#2e2420",tail:"#2e2420",beak:"#e8e0d0",leg:"#c8b8a8"},
 sym:{keys:["purification","renewal","new vision"],src:"andrews",why:"Andrews associates vultures with purification and with death and rebirth — they clean what's finished so life can go on. A sign that something is being cleared for renewal."}},
{id:"great-horned-owl",name:"Great Horned Owl",size:"large",colors:["brown","gray","white","orange"],shape:"owl",tufts:true,months:"all",
 where:"Golden Gate Park, the Presidio, Lake Merced; deep hoots on winter nights when they court.",
 both:{head:"#8a7058",face:"#c8905a",back:"#7a6048",belly:"#c8b8a0",wing:"#6a5040",eye:YL,throat:W,bars:true},
 sym:{keys:["wisdom","seeing in the dark","mystery"],src:"andrews",why:"Andrews connects owls with wisdom, with seeing what's hidden, and with the mysteries of the night. An owl can be a sign that you already know more than you think."}},
{id:"barn-owl",name:"Barn Owl",size:"large",colors:["white","orange","gray"],shape:"owl",months:"all",
 where:"Hunts at night over open parks and fields; screechy call.",
 both:{head:"#d8b070",face:W,back:"#d8a860",belly:"#f4ecdc",wing:"#c8a870",eye:K,heart:true,spots:true},
 sym:{keys:["silent wisdom","night vision","mystery"],src:"family",why:"Carries Andrews' owl themes of wisdom and deep seeing. Barn owls fly in near-total silence and find their prey by sound alone — listening as a kind of seeing."}}
];


const YOUNG={
 "american-robin":[{head:"#4a4a4e",back:"#6a6560",belly:"#e0a070",wing:"#5f5a55",tail:"#3a3a3e",beak:"#6a5a40",spots:true,eyeRing:W},"Speckled breast and paler orange — seen spring and summer."],
 "western-bluebird":[{head:"#8a909a",back:"#7a808a",belly:"#e8e2d8",wing:"#6a8ac8",tail:"#6a8ac8",spots:true,eyeRing:W},"Gray-brown and speckled, with blue only in the wings and tail."],
 "western-gull":[{head:"#8a7a6a",back:"#7a6a5a",belly:"#9a8a7a",wing:"#6a5a4a",tail:"#4a3a30",beak:"#2a2a2a",leg:"#c8a8a0",scales:true},"Mottled brown with a dark bill; takes about four years to become gray and white."],
 "black-crowned-night-heron":[{head:"#8a6a4a",back:"#7a5a3e",belly:"#d8c8b0",wing:"#7a5a3e",tail:"#7a5a3e",beak:"#c8b040",leg:"#c8c050",eye:"#e0802a",streaks:true},"Brown with white spots and streaks, orange eye — looks like a different bird."],
 "great-blue-heron":[{head:"#3a3a40",neck:"#9a96a0",back:"#6a7282",belly:"#7a8292",wing:"#6a7282",tail:"#6a7282",beak:"#8a8050",leg:"#4a4038"},"Dark cap, no plumes, duller bill."],
 "red-tailed-hawk":[{head:"#7a5a3e",back:"#6a4a30",belly:"#f0e8d8",wing:"#6a4a30",tail:"#8a7050",beak:"#3a3a3a",leg:YL,eye:"#d8c060",patch:{at:"bellyband",c:"#6a4a30"},streaks:true},"Brown banded tail — the red comes in its second year — and a pale eye."],
 "coopers-hawk":[{head:"#7a5a3e",back:"#6a5038",belly:"#f0e8dc",wing:"#6a5038",tail:"#6a5038",beak:"#3a3a3a",leg:YL,eye:YL,streaks:true},"Brown above, streaked below, yellow eye."],
 "white-crowned-sparrow":[{head:"#a7a09a",cap:"#7a5a3e",crownStripe:"#c8a878",back:"#8a6a4a",belly:"#c9c2b8",wing:"#7a5a3e",tail:"#7a5a3e",beak:"#e8b24a",bars:true,streaks:true},"Brown-and-tan head stripes instead of black and white."],
 "dark-eyed-junco":[{head:"#7a6a5a",back:"#8a6a50",belly:"#d8ccbc",wing:"#6a5a4a",tail:"#4a4a4a",beak:"#d8b0a8",streaks:true},"Streaky brown all over, in summer."],
 "european-starling":[{head:"#6a625a",back:"#6a625a",belly:"#7a7268",wing:"#5a5450",tail:"#5a5450",beak:"#3a3a3a"},"Plain gray-brown in summer."],
 "brown-pelican":[{head:"#8a7a6a",back:"#8a7a6a",belly:"#e8e2d8",wing:"#7a6a5a",tail:"#6a5a4a",throat:"#8a7a6a",beak:"#a89878"},"Brown head and neck with a white belly."],
 "double-crested-cormorant":[{head:"#5a4e44",back:"#4a4038",belly:"#c8b8a0",throat:"#c8b8a0",wing:"#4a4038",tail:"#3a3028",face:"#e8a04a",beak:"#8a7a5a",eye:"#6a8a8a",scales:true},"Brown with a pale neck and breast."],
 "cedar-waxwing":[{head:"#a8906a",face:"#5a5048",back:"#a08868",belly:"#d8ccaa",wing:"#6e747c",tail:"#6e747c",tailTip:YL,streaks:true},"Streaky below with a fainter mask."],
 "peregrine-falcon":[{head:"#4a3e34",face:"#4a3e34",back:"#5a4a3e",belly:"#e8d8c0",wing:"#5a4a3e",tail:"#5a4a3e",beak:"#3a3a3a",leg:"#b8c8a0",streaks:true,eyeRing:"#a8b8c8"},"Brown above, heavily streaked below."],
 "turkey-vulture":[{head:"#4a4a4a",back:"#3a2e2a",belly:"#3a2e2a",wing:"#2e2420",tail:"#2e2420",beak:"#6a6a6a",leg:"#c8b8a8"},"Gray-black head that reddens with age."],
 "barn-swallow":[{head:"#2e4a8a",throat:"#d8a080",back:"#2e4a8a",belly:"#f0e4d8",wing:"#28407a",tail:"#28407a",fork:true},"Paler throat and belly, shorter tail streamers."],
 "great-horned-owl":[{head:"#a89478",face:"#c8a880",back:"#a08868",belly:"#d8ccb8",wing:"#8a7458",eye:YL,bars:true},"Fluffy and pale, with short ear tufts, in spring."],
 "mallard":null,"annas-hummingbird":null
};
function lookFor(b,sex){
  if(sex==="y"){const y=YOUNG[b.id];if(y)return y[0];const base=Object.assign({},b.f||b.both||b.m);base._muted=true;return base;}
  return b.both||b[sex]||b.m;
}
function youngNote(b){const y=YOUNG[b.id];if(y)return y[1];return b.f?"Young birds look much like the female, a little duller.":"Young birds look much like the adults, a little duller.";}

const BEYOND=[
 {id:"giraffe",size:"xlarge",name:"Giraffe",emoji:"🦒",sym:{keys:["reaching higher","far sight","gentle strength"],src:"folk",why:"The tallest animal sees far ahead and reaches what others can't, while staying gentle. Andrews may discuss giraffes in Animal-Wise; this reading is a common one."}},
 {id:"elephant",size:"xlarge",name:"Elephant",emoji:"🐘",sym:{keys:["memory","family","ancient strength"],src:"folk",why:"Elephants remember, mourn their dead, and move in family groups led by elders. Strength that is also tenderness."}},
 {id:"whale",size:"xlarge",name:"Whale",emoji:"🐋",sym:{keys:["deep song","creation","emotional depth"],src:"andrews",why:"Andrews connects whales with song as creative power and with the depths of feeling and memory."}},
 {id:"wolf",size:"large",name:"Wolf",emoji:"🐺",sym:{keys:["guardianship","loyalty","inner teacher"],src:"andrews",why:"Andrews writes of the wolf as guardian and teacher — loyal to its pack, trusting its own instincts, finding new paths."}},
 {id:"bear",size:"xlarge",name:"Bear",emoji:"🐻",sym:{keys:["inner power","rest","awakening"],src:"andrews",why:"Andrews ties bear to awakening the power of the unconscious — going inward, like hibernation, to come back stronger."}},
 {id:"fox",size:"medium",name:"Fox",emoji:"🦊",sym:{keys:["cleverness","camouflage","adaptability"],src:"andrews",why:"Andrews associates the fox with camouflage, shapeshifting and quiet cleverness — moving through the world unseen when needed."}},
 {id:"deer",size:"large",name:"Deer",emoji:"🦌",sym:{keys:["gentleness","innocence","new adventure"],src:"andrews",why:"Andrews connects deer with gentleness and innocence, and with being gently lured toward new adventures."}},
 {id:"butterfly",size:"tiny",name:"Butterfly",emoji:"🦋",sym:{keys:["transformation","joy","dance"],src:"andrews",why:"Andrews writes about the butterfly as the great symbol of transformation, and of the dance and color of life."}},
 {id:"bee",size:"tiny",name:"Bee",emoji:"🐝",sym:{keys:["sweetness","community","productivity"],src:"andrews",why:"Andrews connects bees with the sweetness of life and fertility, and with working together toward something nourishing."}},
 {id:"snake",size:"medium",name:"Snake",emoji:"🐍",sym:{keys:["transformation","healing","rebirth"],src:"andrews",why:"Andrews ties the snake to transformation, healing and life force — shedding old skin to be reborn."}},
 {id:"turtle",size:"medium",name:"Turtle",emoji:"🐢",sym:{keys:["mother earth","longevity","steady pace"],src:"andrews",why:"Andrews links the turtle with Mother Earth and long life, and with carrying home wherever you go."}},
 {id:"lion",size:"xlarge",name:"Lion",emoji:"🦁",sym:{keys:["courage","sun power","family pride"],src:"folk",why:"A solar animal of courage and rest together — lions spend much of the day relaxing, and the lionesses lead the hunt."}}
];


const LEN={"annas-hummingbird":10,"allens-hummingbird":9,"black-phoebe":17,"american-robin":25,"california-scrub-jay":28,"stellers-jay":32,"common-raven":61,"american-crow":45,"rock-pigeon":32,"mourning-dove":30,"house-finch":14,"lesser-goldfinch":10,"american-goldfinch":12,"white-crowned-sparrow":16,"song-sparrow":15,"dark-eyed-junco":15,"spotted-towhee":19,"california-towhee":22,"chestnut-backed-chickadee":11,"bushtit":9,"pygmy-nuthatch":10,"ruby-crowned-kinglet":10,"yellow-rumped-warbler":13,"townsends-warbler":12,"wilsons-warbler":11,"hooded-oriole":19,"northern-mockingbird":24,"european-starling":21,"brewers-blackbird":23,"red-winged-blackbird":21,"cedar-waxwing":16,"western-bluebird":17,"barn-swallow":17,"downy-woodpecker":16,"northern-flicker":31,"belted-kingfisher":32,"red-masked-parakeet":33,"california-quail":25,"killdeer":25,"hermit-thrush":17,"mallard":58,"bufflehead":35,"canada-goose":95,"western-gull":60,"brown-pelican":125,"double-crested-cormorant":80,"great-blue-heron":120,"great-egret":99,"snowy-egret":60,"black-crowned-night-heron":62,"red-tailed-hawk":52,"coopers-hawk":42,"american-kestrel":25,"peregrine-falcon":43,"turkey-vulture":70,"great-horned-owl":55,"barn-owl":38,
 bee:1.5,butterfly:6,fox:70,snake:120,turtle:40,deer:170,wolf:140,lion:230,bear:240,giraffe:480,elephant:600,whale:1400};
const lenOf=a=>LEN[a.id]??SIZE_LEN[a.size]??100;
let sortBy="guide";
function sortList(list){
  if(sortBy==="small")return [...list].sort((a,b)=>lenOf(a)-lenOf(b));
  if(sortBy==="large")return [...list].sort((a,b)=>lenOf(b)-lenOf(a));
  if(sortBy==="seen")return [...list].sort((a,b)=>sightingsOf(b.id).length-sightingsOf(a.id).length||a.name.localeCompare(b.name));
  return list;
}
function sortRow(){return `<div class="frow sortrow"><span class="flabel">Sort</span>${[["guide","Guide order"],["small","Smallest first"],["large","Largest first"],["seen","Most seen"]].map(([k,l])=>`<button class="chip" data-sort="${k}" aria-pressed="${sortBy===k}">${l}</button>`).join("")}</div>`;}
function wireSort(root,after){root.querySelectorAll("[data-sort]").forEach(b=>b.onclick=()=>{sortBy=b.dataset.sort;root.querySelectorAll("[data-sort]").forEach(x=>x.setAttribute("aria-pressed",x.dataset.sort===sortBy));after();});}


/* Real photos from iNaturalist, checked by eye on 10/01/26: each is the right species, shown as the male/adult, openly licensed.
   [iNaturalist taxon id, "photoId:ext", attribution]. Beyond animals use one representative species (named in INAT_AS).
   To change one, pick a CC-licensed photo on the taxon page and put its id here. */
const INAT={
 "annas-hummingbird":[6317, "85724236:jpeg", "(c) abcdefgewing, some rights reserved (CC BY-NC), uploaded by abcdefgewing"],
 "allens-hummingbird":[6359, "173944350:jpeg", "(c) Matthew Ferretti, some rights reserved (CC BY-NC), uploaded by Matthew Ferretti"],
 "black-phoebe":[17013, "1616631:jpg", "(c) Jack Wolf, some rights reserved (CC BY-ND)"],
 "american-robin":[12727, "34859026:jpg", "(c) John D Reynolds, some rights reserved (CC BY-NC), uploaded by John D Reynolds"],
 "california-scrub-jay":[506118, "52796822:jpg", "(c) Matt K, some rights reserved (CC BY-NC), uploaded by Matt K"],
 "stellers-jay":[8234, "324594834:jpeg", "(c) Dave Drum, some rights reserved (CC BY-NC), uploaded by Dave Drum"],
 "common-raven":[8010, "54389687:jpg", "(c) arbyreed, some rights reserved (CC BY-NC-SA)"],
 "american-crow":[8021, "24115:jpg", "(c) Joe McKenna, some rights reserved (CC BY-NC)"],
 "rock-pigeon":[3017, "466776975:jpg", "(c) Birds of Gilgit-Baltistan, some rights reserved (CC BY-SA)"],
 "mourning-dove":[3454, "14015355:jpg", "(c) Donna Pomeroy, some rights reserved (CC BY-NC), uploaded by Donna Pomeroy"],
 "house-finch":[199840, "56363382:jpg", "(c) Donna Pomeroy, some rights reserved (CC BY-NC), uploaded by Donna Pomeroy"],
 "lesser-goldfinch":[145308, "113951191:jpeg", "(c) David J Barton, some rights reserved (CC BY-NC), uploaded by David J Barton"],
 "american-goldfinch":[145310, "384965723:jpg", "(c) Chris Fisher, some rights reserved (CC BY-NC), uploaded by Chris Fisher"],
 "white-crowned-sparrow":[9176, "65971681:jpg", "(c) uzun, some rights reserved (CC BY-NC), uploaded by uzun"],
 "song-sparrow":[9100, "104749271:jpg", "(c) Ad Konings, some rights reserved (CC BY-NC), uploaded by Ad Konings"],
 "dark-eyed-junco":[10094, "462900958:jpg", "(c) Becky Matsubara, some rights reserved (CC BY)"],
 "spotted-towhee":[9420, "30818274:jpg", "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley"],
 "california-towhee":[73044, "1004:jpg", "(c) Lucina M, some rights reserved (CC BY-NC)"],
 "chestnut-backed-chickadee":[144820, "57455544:jpeg", "(c) Garth Harwood, some rights reserved (CC BY), uploaded by Garth Harwood"],
 "bushtit":[7266, "111125701:jpg", "(c) Kevin Krebs, some rights reserved (CC BY-NC-SA)"],
 "pygmy-nuthatch":[14816, "1299:jpg", "(c) Len Blumin, some rights reserved (CC BY)"],
 "ruby-crowned-kinglet":[1289388, "251475181:jpg", "(c) Ad Konings, some rights reserved (CC BY-NC), uploaded by Ad Konings"],
 "yellow-rumped-warbler":[126562, "195484620:jpg", "(c) John D Reynolds, some rights reserved (CC BY-NC), uploaded by John D Reynolds"],
 "townsends-warbler":[145255, "627894034:jpg", "(c) Braxton L., some rights reserved (CC BY-NC), uploaded by Braxton L."],
 "wilsons-warbler":[145276, "249415681:jpeg", "(c) Jozef K. Richards, some rights reserved (CC BY-NC), uploaded by Jozef K. Richards"],
 "hooded-oriole":[9319, "7747:jpg", "(c) Francesco Veronesi, some rights reserved (CC BY-NC-SA)"],
 "northern-mockingbird":[14886, "142697277:jpg", "(c) Kevin Milazzo, some rights reserved (CC BY-NC-SA)"],
 "european-starling":[14850, "32152001:jpg", "(c) Fran Wiesner, some rights reserved (CC BY-NC-ND), uploaded by Fran Wiesner"],
 "brewers-blackbird":[10325, "615371790:jpg", "(c) Michael Long, some rights reserved (CC BY-NC), uploaded by Michael Long"],
 "red-winged-blackbird":[9744, "40716010:jpg", "(c) Alexander Viduetsky, some rights reserved (CC BY-NC), uploaded by Alexander Viduetsky"],
 "cedar-waxwing":[7428, "450146514:jpeg", "(c) Manny Salas, some rights reserved (CC BY-NC), uploaded by Manny Salas"],
 "western-bluebird":[12937, "16748149:jpg", "(c) uzun, some rights reserved (CC BY-NC), uploaded by uzun"],
 "barn-swallow":[11901, "122469139:jpg", "(c) Ad Konings, some rights reserved (CC BY-NC), uploaded by Ad Konings"],
 "downy-woodpecker":[792988, "402494560:jpeg", "(c) Craig K. Hunt, some rights reserved (CC BY-NC), uploaded by Craig K. Hunt"],
 "northern-flicker":[18236, "180185405:jpeg", "(c) rabbitlady101, some rights reserved (CC BY-NC)"],
 "belted-kingfisher":[2548, "448616451:jpg", "(c) JeffreyGammon, some rights reserved (CC BY-NC), uploaded by JeffreyGammon"],
 "red-masked-parakeet":[367572, "113245781:jpg", "(c) David F. Belmonte, some rights reserved (CC BY), uploaded by David F. Belmonte"],
 "california-quail":[1409, "443842323:jpg", "(c) Caiden, some rights reserved (CC BY-NC), uploaded by Caiden"],
 "killdeer":[4793, "15053771:jpg", "(c) world_lineage, some rights reserved (CC BY-NC), uploaded by world_lineage"],
 "hermit-thrush":[12890, "55985643:jpg", "(c) matthew_wills, some rights reserved (CC BY-NC), uploaded by matthew_wills"],
 "mallard":[6930, "95268822:jpg", "(c) anonymous, some rights reserved (CC BY-SA)"],
 "bufflehead":[6993, "249283060:jpg", "(c) ianhearn, some rights reserved (CC BY-NC)"],
 "canada-goose":[7089, "31186857:jpg", "(c) Thomas J. Bright, some rights reserved (CC BY-NC), uploaded by Thomas J. Bright"],
 "western-gull":[4345, "1877:jpg", "(c) Jamie Chavez, some rights reserved (CC BY-NC)"],
 "brown-pelican":[4328, "74013719:jpg", "(c) BJ Stacey, some rights reserved (CC BY-NC), uploaded by BJ Stacey"],
 "double-crested-cormorant":[1454382, "182713821:jpg", "(c) José Antonio Linage Espinosa, some rights reserved (CC BY-NC), uploaded by José Antonio Linage Espinosa"],
 "great-blue-heron":[4956, "65060931:jpg", "(c) Dan Roach, some rights reserved (CC BY-NC), uploaded by Dan Roach"],
 "great-egret":[144455, "56653891:jpg", "(c) daverowe, some rights reserved (CC BY-NC)"],
 "snowy-egret":[4940, "2415351:jpg", "(c) Greg Lasley, some rights reserved (CC BY-NC), uploaded by Greg Lasley"],
 "black-crowned-night-heron":[4981, "49357930:jpg", "no rights reserved, uploaded by Kyle Nessen"],
 "red-tailed-hawk":[5212, "236676280:jpg", "(c) Liam Huber, some rights reserved (CC BY-NC), uploaded by Liam Huber"],
 "coopers-hawk":[1579017, "170370008:jpg", "(c) Abby Sesselberg, some rights reserved (CC BY-NC), uploaded by Abby Sesselberg"],
 "american-kestrel":[4665, "182751742:jpeg", "(c) rabbitlady101, some rights reserved (CC BY-NC)"],
 "peregrine-falcon":[4647, "212499566:jpg", "(c) nautiboy, some rights reserved (CC BY-NC)"],
 "turkey-vulture":[4756, "52277010:jpg", "(c) Seig, some rights reserved (CC BY), uploaded by Seig"],
 "great-horned-owl":[20044, "14549085:jpg", "(c) Paul G. Johnson, some rights reserved (CC BY-NC-SA), uploaded by Paul G. Johnson"],
 "barn-owl":[20445, "165796939:jpg", "(c) caroline legg, some rights reserved (CC BY)"],
 "giraffe":[42157, "107487820:jpg", "(c) ONG OeBenin, some rights reserved (CC BY-NC), uploaded by ONG OeBenin"],
 "elephant":[43694, "93674728:jpg", "(c) dhfischer, some rights reserved (CC BY), uploaded by dhfischer"],
 "whale":[41566, "338733901:jpg", "(c) John Thorogood, some rights reserved (CC BY-NC), uploaded by John Thorogood"],
 "wolf":[42048, "43410580:jpg", "(c) Brian Starzomski, some rights reserved (CC BY-NC), uploaded by Brian Starzomski"],
 "bear":[41641, "1491897:jpg", "(c) Donna Pomeroy, some rights reserved (CC BY-NC), uploaded by Donna Pomeroy"],
 "fox":[42069, "6568074:jpg", "(c) Joanne Muis Redwood, some rights reserved (CC BY-NC), uploaded by Joanne Muis Redwood"],
 "deer":[42220, "595176639:jpg", "(c) ayden, some rights reserved (CC BY), uploaded by ayden"],
 "butterfly":[48662, "227923335:jpeg", "(c) Alejandro Lopez, some rights reserved (CC BY-NC-SA), uploaded by Alejandro Lopez"],
 "bee":[47219, "389898647:jpeg", "(c) Lê Thanh Hoa, some rights reserved (CC BY-NC), uploaded by Lê Thanh Hoa"],
 "snake":[28362, "154286296:jpg", "(c) John Anderson, some rights reserved (CC BY-NC), uploaded by John Anderson"],
 "turtle":[39771, "9927445:jpg", "(c) Susan Elliott, some rights reserved (CC BY-NC), uploaded by Susan Elliott"],
 "lion":[41964, "9225318:jpg", "(c) seasav, some rights reserved (CC BY-NC-ND), uploaded by seasav"]
};
const INAT_AS={"whale": "Humpback whale", "wolf": "Gray wolf", "bear": "Brown bear", "fox": "Red fox", "deer": "Mule deer (black-tailed)", "butterfly": "Monarch", "bee": "Western honey bee", "snake": "Common garter snake", "turtle": "Painted turtle", "giraffe": "Northern giraffe", "elephant": "African savanna elephant", "lion": "Lion"};
