/* Kindred Creatures — legal protections. Plain script; shares globals with the other js/ files.
   LAWS: species-level rules, shown behind the F / S / C badges (federal, state, city & county).
   OVERALL: rules that cover whole groups (all trees in SF, all plants in parks…), shown on the Laws tab.
   Checked against the code text on 10/02/26 where marked ✓ in the comments; everything else is a
   careful summary to verify before relying on it. Not legal advice. */

const LAW_LEVELS={F:"Federal",S:"California",C:"San Francisco (city & county)"};

const LAWS={
 /* ---------- Federal ---------- */
 mbta:{lv:"F",name:"Migratory Bird Treaty Act",
  short:"Protected bird: no killing, taking, possessing, selling — or disturbing nests and eggs — without a federal permit.",
  what:"Covers the living bird, its feathers and other parts, nests and eggs. “Take” includes pursue, hunt, shoot, wound, kill, trap, capture or collect, or attempt to.",
  allows:"Permits for depredation (after nonlethal steps fail), falconry, rehab, science and more; hunting seasons for game species. Scaring a bird off without harming it isn't a take (except eagles).",
  penalty:"Misdemeanor, strict liability: up to $15,000 and 6 months. Knowingly taking to sell: felony, up to 2 years.",
  note:"Since April 2025 the Interior Department reads the Act as not covering accidental (incidental) deaths (Solicitor's Opinion M-37085); courts are split.",
  cite:"16 U.S.C. §§ 703–712; list at 50 C.F.R. § 10.13 (updated 2023)", url:"https://www.ecfr.gov/current/title-50/chapter-I/subchapter-B/part-10/subpart-B/section-10.13"},
 mbta_no:{lv:"F",info:true,name:"Not on the Migratory Bird Treaty Act list",
  short:"Not covered — the federal list leaves out birds people brought here and most upland game birds.",
  what:"Non-native species (rock pigeon, European starling, house sparrow, the SF wild parrots, mute swan) and birds outside the treaty countries aren't listed.",
  cite:"50 C.F.R. § 10.13; Migratory Bird Treaty Reform Act of 2004"},
 mbta_control:{lv:"F",name:"Federal control order for blackbirds and crows",
  short:"Still MBTA-protected, but a standing control order lets people kill them without a permit when they are damaging crops or property or are a health hazard — with strict conditions and reporting.",
  cite:"50 C.F.R. part 21 (control order for blackbirds, cowbirds, grackles, crows and magpies)"},
 bgepa:{lv:"F",name:"Bald and Golden Eagle Protection Act",
  short:"Extra eagle protection: no take, possession, sale or even disturbance (agitating an eagle enough to injure it or make it abandon a nest) without a permit.",
  what:"Covers live and dead eagles, parts, feathers, nests and eggs. Even scaring eagles off needs a permit, unlike other MBTA birds.",
  allows:"Permits for religious use by tribal members (eagle feathers through the National Eagle Repository), science, and some incidental take.",
  penalty:"Up to $100,000 ($200,000 for organizations) and a year in prison for a first offense; repeat offenses are felonies.",
  cite:"16 U.S.C. §§ 668–668d; 50 C.F.R. part 22"},
 esa:{lv:"F",name:"Endangered Species Act",
  short:"Listed animal: no harming, harassing, killing, capturing or trading it — and “harm” can include destroying its habitat.",
  what:"Endangered animals get the full “take” ban; threatened ones get it too unless a special rule (4(d) rule) says otherwise. Federal agencies must make sure their projects don't jeopardize the species.",
  allows:"Incidental take permits with a habitat conservation plan; recovery and science permits.",
  penalty:"Knowing violations: fines and up to a year in prison; civil penalties too. Anyone can sue to enforce it (citizen suits).",
  cite:"16 U.S.C. §§ 1531–1544 (take ban § 1538)"},
 esa_plant:{lv:"F",name:"Endangered Species Act (plants)",
  short:"Listed plant: illegal to dig up or destroy on federal land (like the Presidio), or anywhere in knowing violation of state law; trade is banned.",
  what:"Plants get narrower protection than animals: on private land the federal ban only bites if you also break a state law or trespass.",
  cite:"16 U.S.C. § 1538(a)(2)"},
 esa_prop:{lv:"F",name:"Endangered Species Act — proposed",
  short:"Proposed for listing; not yet protected by the take ban. A final decision is pending.",
  cite:"16 U.S.C. § 1533"},
 mmpa:{lv:"F",name:"Marine Mammal Protection Act",
  short:"All marine mammals: no hunting, killing, capturing or harassing — and harassment includes getting close enough to change their behavior.",
  what:"NOAA's viewing guideline is to stay 50 yards from seals and sea lions and 100 yards from whales; never feed them. Report stranded animals instead of touching them.",
  allows:"Permits for science, rescue and rehab, some fisheries incidental take, and Alaska Native subsistence.",
  penalty:"Civil fines up to $10,000+ per violation; criminal fines up to $20,000+ and a year in jail.",
  cite:"16 U.S.C. §§ 1361–1423h (take ban § 1372)"},
 whba:{lv:"F",name:"Wild Free-Roaming Horses and Burros Act",
  short:"Wild horses on federal land are protected: no capturing, branding, harassing or killing them.",
  cite:"16 U.S.C. §§ 1331–1340"},
 bigcat:{lv:"F",name:"Big Cat Public Safety Act",
  short:"Private people can't newly own or breed lions, tigers and other big cats, and public contact like cub petting is banned.",
  cite:"Pub. L. 117-243 (2022), amending the Lacey Act, 16 U.S.C. §§ 3371–3372"},
 cites1:{lv:"F",name:"CITES Appendix I (international trade)",
  short:"Threatened with extinction: commercial international trade is banned; any import or export needs permits from both countries.",
  cite:"CITES; carried out in the U.S. through the ESA, 16 U.S.C. § 1538(c), and 50 C.F.R. part 23"},
 cites2:{lv:"F",name:"CITES Appendix II (international trade)",
  short:"Trade is allowed but needs an export permit showing it won't hurt wild populations.",
  cite:"CITES; 50 C.F.R. part 23"},
 sod:{lv:"F",name:"Sudden oak death quarantine",
  short:"San Francisco is inside the regulated area: host plants and their wood, leaves and soil can't be moved out of the area without meeting quarantine rules (nurseries are inspected).",
  cite:"7 C.F.R. § 301.92 (Phytophthora ramorum); state rule 3 C.C.R. § 3700"},

 /* ---------- California ---------- */
 ca3513:{lv:"S",name:"State mirror of the Migratory Bird Treaty Act",
  short:"California makes it a state crime to take or possess any MBTA bird — and since 2025 it locks in the federal list and rules as of January 1, 2025, in case federal protection is weakened.",
  penalty:"Misdemeanor; prosecuted by county DAs and the Attorney General (a Lassen County rancher was fined $50,000 in 2019).",
  cite:"Cal. Fish & Game Code § 3513 (as amended by AB 454, effective 10/6/25) ✓"},
 ca3503:{lv:"S",name:"Bird nests and eggs",
  short:"It's illegal to take, possess or needlessly destroy the nest or eggs of any bird — native or not, listed or not.",
  what:"This is the rule that matters for tree trimming in nesting season (roughly February–August, but SF hummingbirds nest almost all year).",
  cite:"Cal. Fish & Game Code § 3503 ✓"},
 ca35035:{lv:"S",name:"Birds of prey",
  short:"Hawks, falcons and owls (orders Falconiformes and Strigiformes) and their nests and eggs may not be taken, possessed or destroyed.",
  cite:"Cal. Fish & Game Code § 3503.5 ✓"},
 ca3800:{lv:"S",name:"Nongame birds",
  short:"Every bird that occurs naturally in California and isn't a game or fully protected bird is a “nongame bird” and may not be taken.",
  cite:"Cal. Fish & Game Code § 3800 (parts and feathers: § 3801.6) ✓"},
 ca3801:{lv:"S",info:true,name:"Allowed to be taken",
  short:"State law lets people take or possess English sparrows and starlings at any time — and mute swans until 2031.",
  cite:"Cal. Fish & Game Code § 3801 ✓"},
 ca3511:{lv:"S",name:"Fully protected bird",
  short:"California's strongest protection: may not be taken or possessed at any time, and no permit can authorize it (narrow science and recovery exceptions).",
  cite:"Cal. Fish & Game Code § 3511 (list amended by AB 697, eff. 1/1/26) ✓"},
 ca_game:{lv:"S",name:"Game bird",
  short:"A game species: may only be hunted in season with a license, within bag limits (and federal frameworks for migratory game birds). Hunting isn't allowed in SF city parks.",
  cite:"Cal. Fish & Game Code § 3500; Title 14 C.C.R. hunting regulations ✓"},
 ca_game_m:{lv:"S",name:"Game mammal",
  short:"A game species: may only be taken in season with a license and within limits.",
  cite:"Cal. Fish & Game Code § 3950; Title 14 C.C.R."},
 cesa:{lv:"S",name:"California Endangered Species Act",
  short:"State-listed (or candidate) species: no taking, possessing, buying or selling it. Candidates get the same protection while under review.",
  allows:"Incidental take permits if impacts are minimized and fully mitigated; science and recovery permits.",
  cite:"Cal. Fish & Game Code §§ 2080, 2081, 2085 ✓"},
 ca4150:{lv:"S",name:"Nongame mammal",
  short:"A mammal native to California that isn't game, fur-bearing or fully protected may not be taken except as the code allows; trapping them for fur or fun is banned.",
  allows:"Owners may take ones found damaging crops or property (§ 4152).",
  cite:"Cal. Fish & Game Code §§ 4150, 4152 ✓"},
 ca4152:{lv:"S",info:true,name:"Can be removed when damaging property",
  short:"If one is injuring crops or property, the owner or tenant (or their written agent) may take it — following the trapping and humane rules.",
  cite:"Cal. Fish & Game Code § 4152 ✓"},
 ca4000:{lv:"S",name:"Fur-bearing mammal",
  short:"Listed as a furbearer. Commercial and recreational fur trapping is banned in California, and raw fur can't be sold.",
  cite:"Cal. Fish & Game Code §§ 4000, 4005, 4004 (no body-gripping traps) ✓"},
 ca4700:{lv:"S",name:"Fully protected mammal",
  short:"May not be taken or possessed at any time; no permit can authorize it (narrow science and recovery exceptions).",
  cite:"Cal. Fish & Game Code § 4700 ✓"},
 ca4800:{lv:"S",name:"Specially protected mammal (Proposition 117)",
  short:"Mountain lions may not be taken, injured, possessed or sold. Hunting them has been banned since 1990.",
  allows:"Depredation permits and public-safety removal under strict rules.",
  cite:"Cal. Fish & Game Code § 4800 ✓"},
 ca5050:{lv:"S",name:"Fully protected reptile or amphibian",
  short:"May not be taken or possessed at any time; no permit can authorize it.",
  cite:"Cal. Fish & Game Code § 5050 ✓"},
 ca2000:{lv:"S",name:"General take rule",
  short:"No taking wild birds, mammals, fish (which in state law includes crabs and other invertebrates), reptiles or amphibians except as the code and regulations allow — usually with a license, season and limits.",
  cite:"Cal. Fish & Game Code §§ 2000, 45 ✓"},
 ca_ssc:{lv:"S",info:true,name:"Species of special concern",
  short:"Not a legal listing, but agencies must weigh impacts on it under CEQA when approving projects.",
  cite:"CDFW species of special concern list; CEQA Guidelines § 15380"},
 ca_lead:{lv:"S",name:"Lead ammunition ban",
  short:"Lead ammunition is banned for all hunting in California, largely to protect condors from lead poisoning.",
  cite:"Cal. Fish & Game Code § 3004.5"},
 ca_npp:{lv:"S",name:"Native Plant Protection Act",
  short:"Rare or endangered native plants may not be taken, possessed or sold (except as part of selling the land they grow on).",
  cite:"Cal. Fish & Game Code §§ 1900, 1908 ✓"},
 ca_joshua:{lv:"S",name:"Western Joshua Tree Conservation Act",
  short:"A permit from CDFW (with fees for conservation) is needed to remove or harm a western Joshua tree.",
  cite:"Cal. Fish & Game Code § 1927 et seq. (2023)"},
 ca_oak:{lv:"S",name:"Oak woodlands (CEQA)",
  short:"When a county project would convert oak woodland, the county must find it significant and require mitigation such as replanting or conservation easements.",
  cite:"Cal. Public Resources Code § 21083.4"},
 ca_redwood:{lv:"S",name:"Penal Code § 384a names redwood greens",
  short:"Cutting redwood greens (and other plant material) on public land or land that isn't yours, without a notarized written permit, is a misdemeanor.",
  cite:"Cal. Penal Code § 384a ✓"},

 ca_nonnative:{lv:"S",info:true,name:"Introduced species",
  short:"Not native, so the state's nongame protections for “naturally occurring” animals don't reach it. Animal-cruelty law (Penal Code § 597) still applies, and park rules still protect it in parks.",
  cite:"Cal. Fish & Game Code §§ 3800, 4150 (both limited to species occurring naturally in California) ✓"},
 ca_apiary:{lv:"S",info:true,name:"Beekeeping rules",
  short:"Honey bees are managed livestock: California requires beekeepers to register their hives each year with the county agricultural commissioner.",
  cite:"Cal. Food & Agric. Code § 29040 et seq."},
 fs_plants:{lv:"F",name:"National forest rules",
  short:"Damaging, cutting or removing trees and plants in a national forest without a permit is a federal offense — the reason bristlecone groves are fenced and patrolled.",
  cite:"36 C.F.R. § 261.9"},
 nps:{lv:"F",name:"National park rules",
  short:"In national parks and recreation areas (including the Presidio and the GGNRA in SF), picking, digging or disturbing plants and wildlife is banned without a permit.",
  cite:"36 C.F.R. §§ 2.1, 2.2 (Presidio Trust lands: part 1002)"},

 /* ---------- San Francisco ---------- */
 sf_bison:{lv:"C",name:"The Golden Gate Park bison",
  short:"SF's ban on hunting, chasing, harassing or disturbing park animals names the bison paddock in Golden Gate Park specifically.",
  cite:"S.F. Park Code § 5.08 ✓"},
 sf_sharp:{lv:"C",name:"Sharp Park habitat restoration",
  short:"San Francisco's Park Code orders Rec and Park to restore habitat for the California red-legged frog and San Francisco garter snake at Sharp Park (the city-owned golf course in Pacifica), in line with the ESA.",
  cite:"S.F. Park Code § 3.20 ✓"},
 sf_gopher:{lv:"C",name:"Gopher exception in the parks",
  short:"Disturbing or killing animals in SF parks is banned — but moles, gophers, mice, rats and other rodents that the Superintendent of Parks decides are harmful are carved out.",
  cite:"S.F. Park Code § 5.08 ✓"},
 sf_elephant:{lv:"C",name:"Elephants at the SF Zoo",
  short:"No city department or contractor may keep elephants at the SF Zoo without Board of Supervisors approval of a plan with at least 15 acres of habitat.",
  cite:"S.F. Park Code § 5.09 ✓"},
 sf_wildperf:{lv:"C",name:"No wild animal performances",
  short:"San Francisco bans wild or exotic animals performing for public entertainment.",
  cite:"S.F. Health Code Art. 1B ✓"},
 sf_fur:{lv:"C",name:"Fur sales ban",
  short:"Selling fur products is banned in San Francisco.",
  cite:"S.F. Health Code Art. 1D ✓"}
};

/* Rules for whole groups — shown on the Laws tab, not on every card. */
const OVERALL=[
 {lv:"F",title:"Most native birds are federally protected",for:"birds",
  body:"The Migratory Bird Treaty Act covers over 1,000 native species — including year-round residents that never migrate. The short list of SF birds it skips: rock pigeon, European starling, house sparrow, the wild parrots, and California quail.",cite:"16 U.S.C. §§ 703–712; 50 C.F.R. § 10.13"},
 {lv:"F",title:"Endangered and threatened species",for:"all",
  body:"Listed animals can't be harmed, harassed or killed, including by destroying habitat they need. Listed plants are protected on federal land (the Presidio, Golden Gate National Recreation Area) and wherever removing them breaks state law.",cite:"16 U.S.C. § 1538"},
 {lv:"F",title:"Trade in wildlife and plants",for:"all",
  body:"The Lacey Act makes it a federal crime to trade in wildlife or plants taken in violation of any state, federal, tribal or foreign law.",cite:"16 U.S.C. §§ 3371–3378"},
 {lv:"F",title:"Federal parkland",for:"all",
  body:"In the Presidio, Lands End, Ocean Beach, Fort Funston and the rest of the Golden Gate National Recreation Area, disturbing wildlife or collecting plants, flowers, rocks or other natural features is banned without a permit.",cite:"36 C.F.R. §§ 2.1, 2.2 (Presidio Trust lands: 36 C.F.R. part 1002)"},
 {lv:"S",title:"Every bird's nest",for:"birds",
  body:"Taking, possessing or needlessly destroying the nest or eggs of any bird is illegal — the rule that applies when a tree is cut in nesting season. Birds of prey get an added layer (§ 3503.5).",cite:"Cal. Fish & Game Code §§ 3503, 3503.5"},
 {lv:"S",title:"Wild animals in general",for:"animals",
  body:"No taking wild birds, mammals, fish (crabs and other invertebrates count as fish), reptiles or amphibians except as the code allows. Animal cruelty is a crime for any animal.",cite:"Cal. Fish & Game Code § 2000; Cal. Penal Code § 597"},
 {lv:"S",title:"Taking plants from land that isn't yours",for:"plants",
  body:"Cutting or removing trees, shrubs, ferns, herbs, bulbs, flowers or other plant material from public land, highway edges or anyone else's land without the owner's written permit is a misdemeanor (up to $1,000 and 6 months). Under 5 pounds, the permit doesn't need to be notarized — but you still need it. There's no special California poppy law; this is the one that covers poppies too.",cite:"Cal. Penal Code § 384a"},
 {lv:"S",title:"Defensible space and trees near houses",for:"trees",
  body:"In high fire hazard zones, state law requires clearing dead wood and fuel around buildings — but it expressly exempts single trees that are well pruned and maintained. An insurer can only require more clearance than the law if a designated fire official finds it's needed and nothing else would work. A new 5-foot ember-resistant “Zone 0” rule was adopted by the Board of Forestry on 8/19/26; reports conflict on whether it has taken effect, and it only reaches locally designated Very High zones in cities. Trimming dead or dying branches is what it asks of existing trees, not removal.",cite:"Cal. Gov. Code § 51182; Cal. Public Resources Code § 4291"},
 {lv:"S",title:"Rare native plants",for:"plants",
  body:"Plants the Fish and Game Commission lists as rare or endangered can't be taken, possessed or sold.",cite:"Cal. Fish & Game Code §§ 1900–1913, 2080"},
 {lv:"C",title:"Significant trees on private land",for:"trees",
  body:"A tree on private land with any part of its trunk within 10 feet of the sidewalk or street is a “significant tree” if it's over 12 inches in trunk diameter, over 20 feet tall, or has a canopy over 15 feet. Removing one needs a Public Works permit with 30 days' posted notice; anyone can object and get a hearing. Wildlife habitat is one of the factors the Director must weigh.",cite:"S.F. Public Works Code §§ 806(b), 810A"},
 {lv:"C",title:"Street trees and landmark trees",for:"trees",
  body:"Any tree in the public right-of-way is a street tree and needs a permit to remove. Landmark trees are designated one by one by the Board of Supervisors and get the strongest protection.",cite:"S.F. Public Works Code §§ 802, 806, 810"},
 {lv:"C",title:"Penalties for illegal tree removal",for:"trees",
  body:"Infraction ($200, then $400) or misdemeanor (up to $1,000 and 6 months); civil penalties up to $500 a day; and administrative penalties of $10,000 per tree or its replacement value, whichever is greater — $20,000 for repeat violations within a year. Report unpermitted removal to 311.",cite:"S.F. Public Works Code § 811 ✓"},
 {lv:"C",title:"Nothing leaves the parks",for:"plants",
  body:"No removing any tree, wood, bush, turf, shrub, flower, plant, grass, soil or rock from a city park without Rec and Park's permission. Mandatory fines of $50–$500, plus the cost of replacing what was taken. This covers foraging and flower-picking in Golden Gate Park.",cite:"S.F. Park Code §§ 4.06, 4.07 ✓"},
 {lv:"C",title:"Leave park animals in peace",for:"animals",
  body:"No hunting, chasing, trapping, harassing, disturbing, capturing, injuring or killing any animal in a city park (rodent pests the Superintendent designates are the exception). Only dogs, cats and horses may be brought in.",cite:"S.F. Park Code §§ 5.01, 5.08 ✓"},
 {lv:"C",title:"No feeding wild animals in parks",for:"animals",
  body:"Feeding any wild animal in a park — pigeons, parrots, raccoons, coyotes — is unlawful unless the Commission authorizes it for a specific place.",cite:"S.F. Park Code § 5.07 ✓"},
 {lv:"C",title:"Bird-safe buildings",for:"birds",
  body:"New buildings and some additions must use bird-safe glass and design near open space and water, and avoid “bird hazards” anywhere in the city.",cite:"S.F. Planning Code § 139"},
 {lv:"C",title:"Park penalties in general",for:"all",
  body:"Unless a section says otherwise, Park Code violations are infractions (up to $100, then $200, then $500) or misdemeanors (up to $1,000 and 6 months), and vandals pay restoration costs.",cite:"S.F. Park Code § 10.01 ✓"}
];
